services:
  envcan:
    build: ./
    restart: always
    volumes:
     - ./db:/root/retro-env-can-weather-chan/db
     - ./cfg:/root/retro-env-can-weather-chan/cfg
     - ./music:/root/retro-env-can-weather-chan/music
    ports:
      - 8600:8600
    environment: 
      - TZ=Canada/Eastern
# Remove "cfg" below if using a bind mount to store config in local filesystem.
volumes:
  # cfg:
  # db:
