services:
  envcan:
    build: ./
    restart: always
    volumes:
      - type: bind
        source: ./db
        target: /root/retro-env-can-weather-chan/db
      - type: bind
        source: ./cfg
        target: /root/retro-env-can-weather-chan/cfg
      - type: bind
        source: ./music
        target: /root/retro-env-can-weather-chan/music
    ports:
      - 8600:8600
    environment: 
      - TZ=Canada/Eastern
      
